### ISSUE TITLE
Error: could not find commit hash for HEAD  

### ISSUE THREAD

**Issue by dewijones92** [kazi-faas/kazi#4]
```
root@dewiserver:~/code# kazi create hello --registry=YOUR_REGISTRY_NAMESPACE
kazi create hello --registry=docker.io/dewijones92
⠋ Create the project
◼ Install project's dependencies
Error: could not find commit hash for HEAD
    at Degit._cloneWithTar (/usr/lib/node_modules/@kazi-faas/cli/node_modules/degit/dist/index-688c5d50.js:14258:10)
    at Degit.clone (/usr/lib/node_modules/@kazi-faas/cli/node_modules/degit/dist/index-688c5d50.js:14096:15)
    at clone (/usr/lib/node_modules/@kazi-faas/cli/dist/commands/create-project.js:52:19)
    at createProject (/usr/lib/node_modules/@kazi-faas/cli/dist/components/Create.js:60:50)
    at /usr/lib/node_modules/@kazi-faas/cli/dist/components/Create.js:74:9
    at invokePassiveEffectCreate (/usr/lib/node_modules/@kazi-faas/cli/node_modules/react-reconciler/cjs/react-reconciler.development.js:16054:20)
    at Object.invokeGuardedCallbackProd (/usr/lib/node_modules/@kazi-faas/cli/node_modules/react-reconciler/cjs/react-reconciler.development.js:12101:10)
    at invokeGuardedCallback (/usr/lib/node_modules/@kazi-faas/cli/node_modules/react-reconciler/cjs/react-reconciler.development.js:12292:31)
    at flushPassiveEffectsImpl (/usr/lib/node_modules/@kazi-faas/cli/node_modules/react-reconciler/cjs/react-reconciler.development.js:16141:9)
    at unstable_runWithPriority (/usr/lib/node_modules/@kazi-faas/cli/node_modules/scheduler/cjs/scheduler.development.js:468:12)
root@dewiserver:~/code#
```

**Comment by pmbanugo** [comment]
Hi @dewijones92 

I don't know why you're getting that error but this project is no longer maintained and I recommend you checkout the Knative func CLI because they have added many of the improvements I hoped to achieve when I started mine
